// Content Blur Guard - Background Service Worker (Text Only)

const API_BASE = "http://127.0.0.1:8000";

// Maintain tab stats
const tabStats = new Map();

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === "updateStats" && sender.tab) {
    const tabId = sender.tab.id;
    const current = tabStats.get(tabId) || { textBlurred: 0, imagesBlurred: 0 };
    current.textBlurred += message.textBlurred || 0;
    current.imagesBlurred += message.imagesBlurred || 0;
    tabStats.set(tabId, current);

    const total = current.textBlurred + current.imagesBlurred;
    if (total > 0) {
      chrome.action.setBadgeText({ tabId, text: String(total) });
      chrome.action.setBadgeBackgroundColor({ tabId, color: "#EF4444" });
    } else {
      chrome.action.setBadgeText({ tabId, text: "" });
    }
    sendResponse({ ok: true });
    return true;
  }

  if (message.action === "getTabStats") {
    const tabId = message.tabId;
    const stats = tabStats.get(tabId) || { textBlurred: 0, imagesBlurred: 0 };
    sendResponse(stats);
    return true;
  }

  if (message.action === "checkHealth") {
    fetch(`${API_BASE}/health`, { method: "GET" })
      .then((r) => r.json())
      .then((data) => sendResponse({ online: true, data }))
      .catch((err) => sendResponse({ online: false, error: err.message }));
    return true; // async response
  }

  // Handle batch text prediction in background to bypass HTTPS Mixed-Content block
  if (message.action === "predictTextBatch") {
    fetch(`${API_BASE}/predict-text-batch`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ texts: message.texts, threshold: message.threshold }),
    })
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((data) => sendResponse({ ok: true, data }))
      .catch((err) => sendResponse({ ok: false, error: err.message }));
    return true; // async response
  }

  // Image prediction cache to prevent redundant network calls
  const imageCache = new Map();

  // Handle image prediction in background to bypass CORS, anti-hotlinking, and Mixed-Content
  if (message.action === "predictImageUrl") {
    const cacheKey = message.dataUrl ? message.dataUrl.slice(0, 100) : message.url;
    if (imageCache.has(cacheKey)) {
      sendResponse({ ok: true, data: imageCache.get(cacheKey) });
      return true;
    }

    function sendToApi(urlPayload) {
      return fetch(`${API_BASE}/predict-image-url`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: urlPayload, threshold: message.threshold || 0.5 }),
      })
        .then((r) => {
          if (!r.ok) throw new Error(`HTTP ${r.status}`);
          return r.json();
        })
        .then((data) => {
          if (imageCache.size > 250) {
            const firstKey = imageCache.keys().next().value;
            imageCache.delete(firstKey);
          }
          imageCache.set(cacheKey, data);
          sendResponse({ ok: true, data });
        })
        .catch((err) => sendResponse({ ok: false, error: err.message }));
    }

    // 1. If base64 dataUrl was already generated by canvas in content script
    if (message.dataUrl) {
      sendToApi(message.dataUrl);
      return true;
    }

    // 2. If it is an external web image, download blob via background fetch to bypass CORS
    const targetUrl = message.url;
    if (targetUrl.startsWith("http://") || targetUrl.startsWith("https://")) {
      fetch(targetUrl)
        .then((res) => {
          if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
          return res.blob();
        })
        .then((blob) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            sendToApi(reader.result);
          };
          reader.onerror = () => sendToApi(targetUrl);
          reader.readAsDataURL(blob);
        })
        .catch(() => {
          // Fallback to sending original URL directly to server
          sendToApi(targetUrl);
        });
      return true;
    }

    // 3. Local/relative or data URL
    sendToApi(targetUrl);
    return true; // async response
  }
});

// Clean up stats when tab closes
chrome.tabs.onRemoved.addListener((tabId) => {
  tabStats.delete(tabId);
});
